name: Run Python Script Daily

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:       # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true

    - name: Run Options_in_future_date.py script
      run: |
        python Options_in_future_date.py

    - name: Run Politicians_trades.py script
      run: |
        python Politicians_trades.py

    - name: Configure Git to use GitHub token
      run: |
        git config --global user.email "dparedesi@uni.pe"
        git config --global user.name "Daniel"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit CSV files and row count
      run: |
        git add politicians_trades.csv top_100_stock_and_options_data.csv
        git commit -m "Daily update CSV files"
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

