name: Run Python Script Daily

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:       # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true

    - name: Run Options_in_future_date.py script
      run: |
        python Options_in_future_date.py

    - name: Run Politicians_trades.py script
      run: |
        python Politicians_trades.py

    - name: Configure Git to use GitHub token
      run: |
        git config --global user.email "dparedesi@uni.pe"
        git config --global user.name "Daniel"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit CSV files and row count
      run: |
        git add top_100_stock_and_options_data.csv politicians_trades.csv row_count.txt
        git commit -m "Update CSV files and row count"
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check row count and send notification
      run: |
        row_count=$(cat row_count.txt)
        if [ "$row_count" -gt 10 ]; then
          echo "Row count: $row_count"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -d "{\"body\": \"Row count from the latest CSV: $row_count\"}" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments
        else
          echo "Row count is $row_count, no notification needed."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
