name: Run Python Script Daily

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:       # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python scripts in parallel
      run: |
        python Options_in_future_date.py &
        python Politicians_trades.py &
        wait

    - name: Configure Git to use GitHub token
      run: |
        git config --global user.email "dparedesi@uni.pe"
        git config --global user.name "Github Actions"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for changes and commit CSV files
      run: |
        git add politicians_trades.csv top_100_stock_and_options_data.csv
        if git diff --staged --exit-code; then
          echo "No changes in CSV files"
        else
          git commit -m "Daily update CSV files"
          git push origin HEAD:${{ github.ref }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}